version: '2'
services:
  server:
    image: ronaldtanner/timesystem-server:latest
    volumes:
      - "./tmp:/tmp"
  client:
    image: ronaldtanner/timesystem-client:latest
    links:
      - server
    environment:
      timeserver: server
