version: "2"

services:
  db:
    container_name: "mysql-server-5.7"
    image: "mysql:5.7"
    ports:
      - "6603:3306"
    volumes:
      - "/Users/thomas/storage/docker/mysql57-datadir:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      
  web:
    container_name: "php-7.1"
    image: "php:7.1-apache"
    ports:
      - "80:80"  
    volumes:
      - "/Users/thomas/WebServer/www:/var/www/html"
