version: "2"

services:
  mysql-server:
    image: "mysql:5.7"
    environment:
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - "6603:3306"
    volumes:
     - "/Users/thomas/storage/docker/mysql57-datadir:/var/lib/mysql"

